import { colors, PlayerData, SectorData } from "@/types";

export const sectorsData: SectorData[] = [
  {
    id: 1,
    name: "GO",
    players: [],
    position: { x: 0, y: 0 },
    type: "corner",
    color: colors.pastelgreen,
    rollType: "voting",
  },
  {
    id: 2,
    name: "Mediterranean Avenue",
    position: { x: 1, y: 0 },
    players: [],
    type: "property",
    color: colors.brown,
    rollType: "auc",
  },
  {
    id: 3,
    name: "Community Chest 1",
    position: { x: 2, y: 0 },
    players: [],
    type: "community_chest",
    color: colors.pastelgreen,
    rollType: "steam",
  },
  {
    id: 4,
    name: "Baltic Avenue",
    position: { x: 3, y: 0 },
    players: [],
    type: "property",
    color: colors.brown,
    rollType: "auc",
  },
  {
    id: 5,
    name: "Income Tax",
    position: { x: 4, y: 0 },
    players: [],
    type: "property",
    color: colors.brown,
    rollType: "auc",
  },
  {
    id: 6,
    name: "Reading Railroad",
    position: { x: 5, y: 0 },
    players: [],
    type: "railroad",
    color: colors.pastelgreen,
    rollType: "steam",
  },
  {
    id: 7,
    name: "Oriental Avenue",
    position: { x: 6, y: 0 },
    players: [],
    type: "property",
    color: colors.lightblue,
    rollType: "auc",
  },
  {
    id: 8,
    name: "Chance 1",
    position: { x: 7, y: 0 },
    players: [],
    type: "chance",
    color: colors.pastelgreen,
    rollType: "steam",
  },
  {
    id: 9,
    name: "Vermont Avenue",
    position: { x: 8, y: 0 },
    players: [],
    type: "property",
    color: colors.lightblue,
    rollType: "auc",
  },
  {
    id: 10,
    name: "Connecticut Avenue",
    position: { x: 9, y: 0 },
    players: [],
    type: "property",
    color: colors.lightblue,
    rollType: "auc",
  },
  {
    id: 11,
    name: "Jail / Just Visiting",
    position: { x: 10, y: 0 },
    players: [],
    type: "corner",
    color: colors.pastelgreen,
    rollType: "steam",
  },
  {
    id: 12,
    name: "St. Charles Place",
    position: { x: 10, y: 1 },
    players: [],
    type: "property",
    color: colors.pink,
    rollType: "auc",
  },
  {
    id: 13,
    name: "Electric Company",
    position: { x: 10, y: 2 },
    players: [],
    type: "utility",
    color: colors.pastelgreen,
    rollType: "steam",
  },
  {
    id: 14,
    name: "States Avenue",
    position: { x: 10, y: 3 },
    players: [],
    type: "property",
    color: colors.pink,
    rollType: "auc",
  },
  {
    id: 15,
    name: "Virginia Avenue",
    position: { x: 10, y: 4 },
    players: [],
    type: "property",
    color: colors.pink,
    rollType: "auc",
  },
  {
    id: 16,
    name: "Pennsylvania Railroad",
    position: { x: 10, y: 5 },
    players: [],
    type: "railroad",
    color: colors.pastelgreen,
    rollType: "steam",
  },
  {
    id: 17,
    name: "St. James Place",
    position: { x: 10, y: 6 },
    players: [],
    type: "property",
    color: colors.orange,
    rollType: "auc",
  },
  {
    id: 18,
    name: "Community Chest 2",
    position: { x: 10, y: 7 },
    players: [],
    type: "community_chest",
    color: colors.pastelgreen,
    rollType: "steam",
  },
  {
    id: 19,
    name: "Tennessee Avenue",
    position: { x: 10, y: 8 },
    players: [],
    type: "property",
    color: colors.orange,
    rollType: "auc",
  },
  {
    id: 20,
    name: "New York Avenue",
    position: { x: 10, y: 9 },
    players: [],
    type: "property",
    color: colors.orange,
    rollType: "auc",
  },
  {
    id: 21,
    name: "Free Parking",
    position: { x: 10, y: 10 },
    players: [],
    type: "corner",
    color: colors.pastelgreen,
    rollType: "voting",
  },
  {
    id: 22,
    name: "Kentucky Avenue",
    position: { x: 9, y: 10 },
    players: [],
    type: "property",
    color: colors.red,
    rollType: "auc",
  },
  {
    id: 23,
    name: "Chance 2",
    position: { x: 8, y: 10 },
    players: [],
    type: "chance",
    color: colors.pastelgreen,
    rollType: "steam",
  },
  {
    id: 24,
    name: "Indiana Avenue",
    position: { x: 7, y: 10 },
    players: [],
    type: "property",
    color: colors.red,
    rollType: "auc",
  },
  {
    id: 25,
    name: "Illinois Avenue",
    position: { x: 6, y: 10 },
    players: [],
    type: "property",
    color: colors.red,
    rollType: "auc",
  },
  {
    id: 26,
    name: "B. & O. Railroad",
    position: { x: 5, y: 10 },
    players: [],
    type: "railroad",
    color: colors.pastelgreen,
    rollType: "steam",
  },
  {
    id: 27,
    name: "Atlantic Avenue",
    position: { x: 4, y: 10 },
    players: [],
    type: "property",
    color: colors.yellow,
    rollType: "auc",
  },
  {
    id: 28,
    name: "Ventnor Avenue",
    position: { x: 3, y: 10 },
    players: [],
    type: "property",
    color: colors.yellow,
    rollType: "auc",
  },
  {
    id: 29,
    name: "Water Works",
    position: { x: 2, y: 10 },
    players: [],
    type: "utility",
    color: colors.pastelgreen,
    rollType: "steam",
  },
  {
    id: 30,
    name: "Marvin Gardens",
    position: { x: 1, y: 10 },
    players: ["2"],
    type: "property",
    color: colors.yellow,
    rollType: "auc",
  },
  {
    id: 31,
    name: "Go To Jail",
    position: { x: 0, y: 10 },
    players: [],
    type: "corner",
    color: colors.pastelgreen,
    rollType: "steam",
  },
  {
    id: 32,
    name: "Pacific Avenue",
    position: { x: 0, y: 9 },
    players: [],
    type: "property",
    color: colors.green,
    rollType: "auc",
  },
  {
    id: 33,
    name: "North Carolina Avenue",
    position: { x: 0, y: 8 },
    players: [],
    type: "property",
    color: colors.green,
    rollType: "auc",
  },
  {
    id: 34,
    name: "Community Chest 3",
    position: { x: 0, y: 7 },
    players: [],
    type: "community_chest",
    color: colors.pastelgreen,
    rollType: "steam",
  },
  {
    id: 35,
    name: "Pennsylvania Avenue",
    position: { x: 0, y: 6 },
    players: [],
    type: "property",
    color: colors.green,
    rollType: "auc",
  },
  {
    id: 36,
    name: "Short Line",
    position: { x: 0, y: 5 },
    players: ["1"],
    type: "railroad",
    color: colors.pastelgreen,
    rollType: "steam",
  },
  {
    id: 37,
    name: "Chance 3",
    position: { x: 0, y: 4 },
    players: [],
    type: "chance",
    color: colors.pastelgreen,
    rollType: "steam",
  },
  {
    id: 38,
    name: "Park Place",
    position: { x: 0, y: 3 },
    players: [],
    type: "property",
    color: colors.blue,
    rollType: "auc",
  },
  {
    id: 39,
    name: "Luxury Tax",
    position: { x: 0, y: 2 },
    players: [],
    type: "tax",
    color: colors.pastelgreen,
    rollType: "steam",
  },
  {
    id: 40,
    name: "Boardwalk",
    position: { x: 0, y: 1 },
    players: [],
    type: "property",
    color: colors.blue,
    rollType: "auc",
  },
];

export const playersData: PlayerData[] = [
  {
    id: "1",
    sectorId: 38,
    name: "Player 1",
    color: colors.green,
  },
  {
    id: "2",
    sectorId: 25,
    name: "Player 2",
    color: colors.pink,
  },
];


export const myPlayerData: PlayerData = playersData[0];
