import {
  GameReviewType,
  FrontendCardData,
  SectorData,
  playerColors,
  PlayerFrontendData,
  BackendPlayerData,
  BonusCardType,
} from '@/lib/types';

import { FALLBACK_GAME_POSTER } from '@/lib/constants';

export const sectorsData: SectorData[] = [
  {
    id: 1,
    name: 'Улица Базовая',
    position: { x: 0, y: 0 },
    type: 'start-corner',
    color: 'pastelgreen',
    rollType: 'voting',
  },
  {
    id: 2,
    name: 'Переулок Пепеговский',
    position: { x: 1, y: 0 },
    type: 'property',
    color: 'brown',
    rollType: 'auc',
  },
  {
    id: 3,
    name: 'Улица Дурки',
    position: { x: 2, y: 0 },
    type: 'bonus',
    color: 'pastelgreen',
    rollType: 'steam',
  },
  {
    id: 4,
    name: 'Улица Донатная',
    position: { x: 3, y: 0 },
    type: 'property',
    color: 'brown',
    rollType: 'auc',
  },
  {
    id: 5,
    name: 'Улица Идейная',
    position: { x: 4, y: 0 },
    type: 'property',
    color: 'brown',
    rollType: 'auc',
  },
  {
    id: 6,
    name: 'Улица Тихого Дэна',
    position: { x: 5, y: 0 },
    type: 'railroad',
    color: 'pastelgreen',
    rollType: 'steam',
  },
  {
    id: 7,
    name: 'Улица Рандомная',
    position: { x: 6, y: 0 },
    type: 'property',
    color: 'lightblue',
    rollType: 'auc',
  },
  {
    id: 8,
    name: 'Улица Колескина',
    position: { x: 7, y: 0 },
    type: 'bonus',
    color: 'pastelgreen',
    rollType: 'steam',
  },
  {
    id: 9,
    name: 'Улица Ауково',
    position: { x: 8, y: 0 },
    type: 'property',
    color: 'lightblue',
    rollType: 'auc',
  },
  {
    id: 10,
    name: 'Переулок Таа',
    position: { x: 9, y: 0 },
    type: 'property',
    color: 'lightblue',
    rollType: 'auc',
  },
  {
    id: 11,
    name: 'Тюрьма 1',
    position: { x: 10, y: 0 },
    type: 'prison',
    color: 'pastelgreen',
    rollType: 'steam',
  },
  {
    id: 12,
    name: 'Переулок Аниме',
    position: { x: 10, y: 1 },
    type: 'property',
    color: 'pink',
    rollType: 'auc',
  },
  {
    id: 13,
    name: 'Улица Бана',
    position: { x: 10, y: 2 },
    type: 'bonus',
    color: 'pastelgreen',
    rollType: 'steam',
  },
  {
    id: 14,
    name: 'Улица Жокерге',
    position: { x: 10, y: 3 },
    type: 'property',
    color: 'pink',
    rollType: 'auc',
  },
  {
    id: 15,
    name: 'Улица кинотетр Синема"',
    position: { x: 10, y: 4 },
    type: 'property',
    color: 'pink',
    rollType: 'auc',
  },
  {
    id: 16,
    name: 'Улица 1984 года',
    position: { x: 10, y: 5 },
    type: 'railroad',
    color: 'pastelgreen',
    rollType: 'steam',
  },
  {
    id: 17,
    name: 'Улица Красивская',
    position: { x: 10, y: 6 },
    type: 'property',
    color: 'orange',
    rollType: 'auc',
  },
  {
    id: 18,
    name: 'Переулок Чатовский',
    position: { x: 10, y: 7 },
    type: 'bonus',
    color: 'pastelgreen',
    rollType: 'steam',
  },
  {
    id: 19,
    name: 'Улица Кубическая',
    position: { x: 10, y: 8 },
    type: 'property',
    color: 'orange',
    rollType: 'auc',
  },
  {
    id: 20,
    name: 'Переулок Дропа',
    position: { x: 10, y: 9 },
    type: 'property',
    color: 'orange',
    rollType: 'auc',
  },
  {
    id: 21,
    name: 'Парковка',
    position: { x: 10, y: 10 },
    type: 'parking',
    color: 'pastelgreen',
    rollType: 'voting',
  },
  {
    id: 22,
    name: 'Переулок Бредикова',
    position: { x: 9, y: 10 },
    type: 'property',
    color: 'red',
    rollType: 'auc',
  },
  {
    id: 23,
    name: 'Улица имени Кала Засто',
    position: { x: 8, y: 10 },
    type: 'bonus',
    color: 'pastelgreen',
    rollType: 'steam',
  },
  {
    id: 24,
    name: 'Улица Стимовская',
    position: { x: 7, y: 10 },
    type: 'property',
    color: 'red',
    rollType: 'auc',
  },
  {
    id: 25,
    name: 'Переулок Арольфина',
    position: { x: 6, y: 10 },
    type: 'property',
    color: 'red',
    rollType: 'auc',
  },
  {
    id: 26,
    name: 'Улица Хуховая',
    position: { x: 5, y: 10 },
    type: 'railroad',
    color: 'pastelgreen',
    rollType: 'steam',
  },
  {
    id: 27,
    name: 'Переулок Ауковый',
    position: { x: 4, y: 10 },
    type: 'property',
    color: 'yellow',
    rollType: 'auc',
  },
  {
    id: 28,
    name: 'Улица Форсена',
    position: { x: 3, y: 10 },
    type: 'property',
    color: 'yellow',
    rollType: 'auc',
  },
  {
    id: 29,
    name: 'Переулок Чомик',
    position: { x: 2, y: 10 },
    type: 'bonus',
    color: 'pastelgreen',
    rollType: 'steam',
  },
  {
    id: 30,
    name: 'Переулок Сужающихся Домов',
    position: { x: 1, y: 10 },
    type: 'property',
    color: 'yellow',
    rollType: 'auc',
  },
  {
    id: 31,
    name: 'Тюрьма 2',
    position: { x: 0, y: 10 },
    type: 'prison',
    color: 'pastelgreen',
    rollType: 'steam',
  },
  {
    id: 32,
    name: 'Улица Уродская',
    position: { x: 0, y: 9 },
    type: 'property',
    color: 'green',
    rollType: 'auc',
  },
  {
    id: 33,
    name: 'Переулок 40-разовый',
    position: { x: 0, y: 8 },
    type: 'property',
    color: 'green',
    rollType: 'auc',
  },
  {
    id: 34,
    name: 'Улица Сратьная',
    position: { x: 0, y: 7 },
    type: 'bonus',
    color: 'pastelgreen',
    rollType: 'steam',
  },
  {
    id: 35,
    name: 'Улица Соточно-каловая',
    position: { x: 0, y: 6 },
    type: 'property',
    color: 'green',
    rollType: 'auc',
  },
  {
    id: 36,
    name: 'Улица Вихарькова',
    position: { x: 0, y: 5 },
    type: 'railroad',
    color: 'pastelgreen',
    rollType: 'steam',
  },
  {
    id: 37,
    name: 'Переулок Агуш',
    position: { x: 0, y: 4 },
    type: 'property',
    color: 'blue',
    rollType: 'auc',
  },
  {
    id: 38,
    name: 'Переулок Кэнникэта',
    position: { x: 0, y: 3 },
    type: 'property',
    color: 'blue',
    rollType: 'auc',
  },
  {
    id: 39,
    name: 'Улица Паст',
    position: { x: 0, y: 2 },
    type: 'bonus',
    color: 'pastelgreen',
    rollType: 'steam',
  },
  {
    id: 40,
    name: 'Переулок Ган Дона',
    position: { x: 0, y: 1 },
    type: 'property',
    color: 'blue',
    rollType: 'auc',
  },
];

const streetNames = new Set();
for (const sector of sectorsData) {
  if (streetNames.has(sector.name)) {
    console.log('duplicate: ', sector.name, sector.id);
  }
  streetNames.add(sector.name);
}

export const SectorsById: Record<number, SectorData> = Object.fromEntries(
  sectorsData.map(sector => [sector.id, sector])
);

export const PrisonSectors = sectorsData.filter(s => s.type === 'prison');

export const playersData: BackendPlayerData[] = [
  {
    id: 1,
    username: 'Praden',
    first_name: 'Денис',
    is_online: true,
    sector_id: 1,
    avatar_link: 'https://github.com/shadcn.png',

    current_game: 'Gothic',
    current_game_updated_at: Math.ceil(Date.now() / 1000),
    current_game_duration: 86976,
    current_game_cover: FALLBACK_GAME_POSTER,
    online_count: 50,
    current_auc_started_at: Math.ceil(Date.now() / 1000),
    current_auc_total_sum: null,
    pointauc_token: 'abc',

    twitch_stream_link: 'https://twitch.tv/praden',
    vk_stream_link: 'https://live.vkvideo.ru/praden',
    kick_stream_link: 'https://kick.com/praden',
    telegram_link: 'https://t.me/praden',
    donation_link: 'https://donate.praden.com',

    total_score: 0,
    maps_completed: 0,

    games: [
      {
        sector_id: 38,
        created_at: Math.ceil(Date.now() / 1000),
        length: '2-5',
        title: 'Haste',
        duration: 0,
        rating: 5,
        review: 'Отличная игра, мне понравилось!',
        status: 'completed',
        vod_links: 'https://www.twitch.tv/videos/123456789',
        cover: FALLBACK_GAME_POSTER,
      },
      {
        sector_id: 5,
        created_at: Math.ceil(Date.now() / 1000),
        length: '25+',
        title: 'Haste',
        duration: 7200,
        rating: 8,
        review: 'Очень интересная игра, много стратегий!',
        status: 'completed',
        vod_links: 'https://www.twitch.tv/videos/987654321',
        cover: FALLBACK_GAME_POSTER,
      },
      {
        sector_id: 5,
        created_at: Math.ceil(Date.now() / 1000),
        length: '20-25',
        title: 'Haste',
        duration: 5400,
        rating: 7,
        review: 'Хорошая игра, но есть недочеты.',
        status: 'completed',
        vod_links: 'https://www.twitch.tv/videos/1122334455',
        cover: FALLBACK_GAME_POSTER,
      },
      {
        sector_id: 5,
        created_at: Math.ceil(Date.now() / 1000),
        length: '15-20',
        title: 'Haste',
        duration: 4800,
        rating: 6,
        review: 'Неплохая игра, но не моя любимая.',
        status: 'completed',
        vod_links: 'https://www.twitch.tv/videos/5566778899',
        cover: FALLBACK_GAME_POSTER,
      },
      {
        sector_id: 5,
        created_at: Math.ceil(Date.now() / 1000),
        length: '10-15',
        title: 'Haste',
        duration: 3000,
        rating: 4,
        review: 'Средняя игра, есть лучше.',
        status: 'completed',
        vod_links: 'https://www.twitch.tv/videos/9988776655',
        cover: FALLBACK_GAME_POSTER,
      },
      {
        sector_id: 5,
        created_at: Math.ceil(Date.now() / 1000),
        length: '5-10',
        title: 'Haste',
        duration: 1800,
        rating: 3,
        review: 'Не очень понравилась, слишком простая.',
        status: 'completed',
        vod_links: 'https://www.twitch.tv/videos/2233445566',
        cover: FALLBACK_GAME_POSTER,
      },
      {
        sector_id: 5,
        created_at: Math.ceil(Date.now() / 1000),
        length: '2-5',
        title: 'Haste',
        duration: 1200,
        rating: 2,
        review: 'Не понравилась, слишком скучная.',
        status: 'completed',
        vod_links: 'https://www.twitch.tv/videos/6677889900',
        cover: FALLBACK_GAME_POSTER,
      },
      {
        sector_id: 5,
        created_at: Math.ceil(Date.now() / 1000),
        length: 'drop',
        title: 'Haste',
        duration: null,
        rating: 1,
        review: 'Не смог пройти, игра не зашла.',
        status: 'drop',
        vod_links: null,
        cover: FALLBACK_GAME_POSTER,
      },
    ],
    bonus_cards: [],
  },
  {
    id: 2,
    sector_id: 5,
    username: 'Player-2',
    first_name: 'Илья',
    is_online: false,
    avatar_link: 'https://github.com/shadcn.png',

    current_game: 'Gothic',
    current_game_updated_at: Math.ceil(Date.now() / 1000),
    current_game_duration: 60,
    current_game_cover: FALLBACK_GAME_POSTER,
    online_count: 50,
    current_auc_started_at: Math.ceil(Date.now() / 1000),
    current_auc_total_sum: null,
    pointauc_token: 'abc',

    twitch_stream_link: 'https://twitch.tv/praden',
    vk_stream_link: 'https://live.vkvideo.ru/praden',
    kick_stream_link: 'https://kick.com/praden',
    telegram_link: 'https://t.me/praden',
    donation_link: 'https://donate.praden.com',

    maps_completed: 0,

    total_score: 5000,
    games: [
      {
        sector_id: 24,
        created_at: Math.ceil(Date.now() / 1000),
        length: '25+',
        title: 'Haste',
        duration: 7200,
        rating: 9,
        review: 'Прекрасная игра, очень понравилась!',
        status: 'completed',
        vod_links: 'https://www.twitch.tv/videos/123456789',
        cover: FALLBACK_GAME_POSTER,
      },
      {
        sector_id: 2,
        created_at: Math.ceil(Date.now() / 1000),
        length: '15-20',
        title: 'Haste',
        duration: 5400,
        rating: 6,
        review: 'Неплохая игра, но есть недочеты.',
        status: 'completed',
        vod_links: 'https://www.twitch.tv/videos/987654321',
        cover: FALLBACK_GAME_POSTER,
      },
      {
        sector_id: 5,
        created_at: Math.ceil(Date.now() / 1000),
        length: '25+',
        title: 'Haste',
        duration: 6000,
        rating: 8,
        review: 'Очень интересная игра, много стратегий!',
        status: 'completed',
        vod_links: 'https://www.twitch.tv/videos/1122334455',
        cover: FALLBACK_GAME_POSTER,
      },
      {
        sector_id: 5,
        created_at: Math.ceil(Date.now() / 1000),
        length: '20-25',
        title: 'Haste',
        duration: 4800,
        rating: 7,
        review: 'Хорошая игра, но есть недочеты.',
        status: 'completed',
        vod_links: 'https://www.twitch.tv/videos/5566778899',
        cover: FALLBACK_GAME_POSTER,
      },
      {
        sector_id: 5,
        created_at: Math.ceil(Date.now() / 1000),
        length: '15-20',
        title: 'Haste',
        duration: 3600,
        rating: 5,
        review: 'Отличная игра, мне понравилось!',
        status: 'completed',
        vod_links: 'https://www.twitch.tv/videos/9988776655',
        cover: FALLBACK_GAME_POSTER,
      },
      {
        sector_id: 5,
        created_at: Math.ceil(Date.now() / 1000),
        length: '10-15',
        title: 'Haste',
        duration: 2400,
        rating: 4,
        review: 'Средняя игра, есть лучше.',
        status: 'completed',
        vod_links: 'https://www.twitch.tv/videos/2233445566',
        cover: FALLBACK_GAME_POSTER,
      },
      {
        sector_id: 5,
        created_at: Math.ceil(Date.now() / 1000),
        length: '5-10',
        title: 'Haste',
        duration: 1200,
        rating: 3,
        review: 'Не очень понравилась, слишком простая.',
        status: 'completed',
        vod_links: 'https://www.twitch.tv/videos/6677889900',
        cover: FALLBACK_GAME_POSTER,
      },
      {
        sector_id: 5,
        created_at: Math.ceil(Date.now() / 1000),
        length: '2-5',
        title: 'Haste',
        duration: 600,
        rating: 2,
        review: 'Не понравилась, слишком скучная.',
        status: 'completed',
        vod_links: 'https://www.twitch.tv/videos/1234567890',
        cover: FALLBACK_GAME_POSTER,
      },
      {
        sector_id: 5,
        created_at: Math.ceil(Date.now() / 1000),
        length: 'drop',
        title: 'Haste',
        duration: null,
        rating: 1,
        review: 'Не смог пройти, игра не зашла.',
        status: 'drop',
        vod_links: null,
        cover: FALLBACK_GAME_POSTER,
      },
    ],
    bonus_cards: [
      {
        bonus_type: 'adjust-roll-by1',
        received_at: Math.ceil(Date.now() / 1000),
        received_on_sector: 5,
      },
    ],
  },
  {
    id: 3,
    sector_id: 5,
    username: 'Player-3',
    first_name: 'Илья',
    is_online: true,
    avatar_link: 'https://github.com/shadcn.png',
    current_game: 'Gothic',
    current_game_updated_at: Math.ceil(Date.now() / 1000),
    current_game_duration: 60,
    current_game_cover: FALLBACK_GAME_POSTER,
    online_count: 50,
    current_auc_started_at: Math.ceil(Date.now() / 1000),
    current_auc_total_sum: null,
    pointauc_token: 'abc',

    twitch_stream_link: 'https://twitch.tv/praden',
    vk_stream_link: 'https://live.vkvideo.ru/praden',
    kick_stream_link: 'https://kick.com/praden',
    telegram_link: 'https://t.me/praden',
    donation_link: 'https://donate.praden.com',

    total_score: 200,
    maps_completed: 1,

    games: [
      {
        sector_id: 2,
        created_at: Math.ceil(Date.now() / 1000),
        length: '5-10',
        title: 'Haste',
        duration: 2400,
        rating: 4,
        review: 'Средняя игра, есть лучше.',
        status: 'completed',
        vod_links: 'https://www.twitch.tv/videos/2233445566',
        cover: FALLBACK_GAME_POSTER,
      },
      {
        sector_id: 5,
        created_at: Math.ceil(Date.now() / 1000),
        length: '10-15',
        title: 'Haste',
        duration: 1800,
        rating: 3,
        review: 'Не очень понравилась, слишком простая.',
        status: 'completed',
        vod_links: 'https://www.twitch.tv/videos/6677889900',
        cover: FALLBACK_GAME_POSTER,
      },
    ],
    bonus_cards: [],
  },
  {
    id: 4,
    sector_id: 5,
    username: 'Player-4',
    first_name: 'Илья',
    is_online: false,
    avatar_link: 'https://github.com/shadcn.png',
    current_game: 'Gothic',
    current_game_updated_at: Math.ceil(Date.now() / 1000),
    current_game_duration: 60,
    current_game_cover: FALLBACK_GAME_POSTER,
    online_count: 50,
    current_auc_started_at: Math.ceil(Date.now() / 1000),
    current_auc_total_sum: null,
    pointauc_token: 'abc',

    twitch_stream_link: 'https://twitch.tv/praden',
    vk_stream_link: 'https://live.vkvideo.ru/praden',
    kick_stream_link: 'https://kick.com/praden',
    telegram_link: 'https://t.me/praden',
    donation_link: 'https://donate.praden.com',

    total_score: 200,
    maps_completed: 2,

    games: [
      {
        sector_id: 2,
        created_at: Math.ceil(Date.now() / 1000),
        length: 'drop',
        title: 'Haste',
        duration: null,
        rating: 1,
        review: 'Не смог пройти, игра не зашла.',
        status: 'drop',
        vod_links: null,
        cover: FALLBACK_GAME_POSTER,
      },
    ],
    bonus_cards: [],
  },
  {
    id: 5,
    sector_id: 5,
    username: 'Player-5',
    first_name: 'Илья',
    is_online: false,
    avatar_link: 'https://github.com/shadcn.png',
    current_game: 'Gothic',
    current_game_updated_at: Math.ceil(Date.now() / 1000),
    current_game_duration: 60,
    current_game_cover: FALLBACK_GAME_POSTER,
    online_count: 50,
    current_auc_started_at: Math.ceil(Date.now() / 1000),
    current_auc_total_sum: null,
    pointauc_token: 'abc',

    twitch_stream_link: 'https://twitch.tv/praden',
    vk_stream_link: 'https://live.vkvideo.ru/praden',
    kick_stream_link: 'https://kick.com/praden',
    telegram_link: 'https://t.me/praden',
    donation_link: 'https://donate.praden.com',

    total_score: 200,
    maps_completed: 0,
    games: [
      {
        sector_id: 2,
        created_at: Math.ceil(Date.now() / 1000),
        length: '2-5',
        title: 'Haste',
        duration: 1200,
        rating: 2,
        review: 'Не понравилась, слишком скучная.',
        status: 'completed',
        vod_links:
          'https://www.twitch.tv/videos/1234567890, https://www.twitch.tv/videos/1234567891, https://www.twitch.tv/videos/1234567892',
        cover: FALLBACK_GAME_POSTER,
      },
    ],
    bonus_cards: [
      {
        bonus_type: 'adjust-roll-by1',
        received_at: Math.ceil(Date.now() / 1000),
        received_on_sector: 5,
      },
    ],
  },
  {
    id: 6,
    sector_id: 5,
    username: 'Player-6',
    first_name: 'Илья',
    is_online: true,
    avatar_link: 'https://github.com/shadcn.png',
    current_game: 'Gothic',
    current_game_updated_at: Math.ceil(Date.now() / 1000),
    current_game_duration: 60,
    current_game_cover: FALLBACK_GAME_POSTER,
    online_count: 50,
    current_auc_started_at: Math.ceil(Date.now() / 1000),
    current_auc_total_sum: null,
    pointauc_token: 'abc',

    twitch_stream_link: 'https://twitch.tv/praden',
    vk_stream_link: 'https://live.vkvideo.ru/praden',
    kick_stream_link: 'https://kick.com/praden',
    telegram_link: 'https://t.me/praden',
    donation_link: 'https://donate.praden.com',

    total_score: 200,
    maps_completed: 0,
    games: [
      {
        sector_id: 10,
        created_at: Math.ceil(Date.now() / 1000),
        length: '15-20',
        title: 'Haste',
        duration: 3600,
        rating: 6,
        review: 'Неплохая игра, но есть недочеты.',
        status: 'completed',
        vod_links: 'https://www.twitch.tv/videos/5566778899',
        cover: FALLBACK_GAME_POSTER,
      },
    ],
    bonus_cards: [
      {
        bonus_type: 'adjust-roll-by1',
        received_at: Math.ceil(Date.now() / 1000),
        received_on_sector: 5,
      },
    ],
  },
  {
    id: 7,
    sector_id: 5,
    username: 'Player-7',
    first_name: 'Илья',
    is_online: true,
    avatar_link: 'https://github.com/shadcn.png',
    current_game: 'Gothic',
    current_game_updated_at: Math.ceil(Date.now() / 1000),
    current_game_duration: 60,
    current_game_cover: FALLBACK_GAME_POSTER,
    online_count: 50,
    current_auc_started_at: Math.ceil(Date.now() / 1000),
    current_auc_total_sum: null,
    pointauc_token: 'abc',

    twitch_stream_link: 'https://twitch.tv/praden',
    vk_stream_link: 'https://live.vkvideo.ru/praden',
    kick_stream_link: 'https://kick.com/praden',
    telegram_link: 'https://t.me/praden',
    donation_link: 'https://donate.praden.com',

    total_score: 200,
    maps_completed: 0,
    games: [
      {
        sector_id: 10,
        created_at: Math.ceil(Date.now() / 1000),
        length: '15-20',
        title: 'Haste',
        duration: 4800,
        rating: 7,
        review: 'Хорошая игра, но есть недочеты.',
        status: 'completed',
        vod_links: 'https://www.twitch.tv/videos/9988776655',
        cover: FALLBACK_GAME_POSTER,
      },
    ],
    bonus_cards: [
      {
        bonus_type: 'adjust-roll-by1',
        received_at: Math.ceil(Date.now() / 1000),
        received_on_sector: 5,
      },
    ],
  },
  {
    id: 8,
    sector_id: 5,
    username: 'Player-8',
    first_name: 'Илья',
    is_online: true,
    avatar_link: 'https://github.com/shadcn.png',
    current_game: null,
    current_game_updated_at: null,
    current_game_cover: null,
    online_count: 50,
    current_auc_started_at: Math.ceil(Date.now() / 1000),
    current_game_duration: 60,
    current_auc_total_sum: null,
    pointauc_token: 'abc',

    twitch_stream_link: 'https://twitch.tv/praden',
    vk_stream_link: 'https://live.vkvideo.ru/praden',
    kick_stream_link: 'https://kick.com/praden',
    telegram_link: 'https://t.me/praden',
    donation_link: 'https://donate.praden.com',

    total_score: 200,
    maps_completed: 0,
    games: [
      {
        sector_id: 10,
        created_at: Math.ceil(Date.now() / 1000),
        length: '5-10',
        title: 'Haste',
        duration: 1800,
        rating: 3,
        review: 'Не очень понравилась, слишком простая.',
        status: 'completed',
        vod_links: 'https://www.twitch.tv/videos/2233445566',
        cover: FALLBACK_GAME_POSTER,
      },
    ],
    bonus_cards: [
      {
        bonus_type: 'adjust-roll-by1',
        received_at: Math.ceil(Date.now() / 1000),
        received_on_sector: 5,
      },
    ],
  },
];

export const frontendCardsData: Record<BonusCardType, FrontendCardData> = {
  'adjust-roll-by1': {
    name: 'Плюс один или минус один',
    picture: 'https://placehold.co/744x1039/FF453A/FF453A',
    description:
      'Возможность добавить/убавить 1 у кубика - после ролла кубиков, но перед началом движения изменить результат кубика.',
  },
  'choose-1-die': {
    name: 'Только 1 кубик',
    picture: 'https://placehold.co/744x1039/0A84FF/0A84FF',
    description:
      'Возможность выбрать только один кубик из трех и сходить на данное значение - после ролла кубикова, но перед началом движения выбрать один кубик.',
  },
  'reroll-game': {
    name: 'Чето пока нехочу)))',
    picture: 'https://placehold.co/744x1039/FF375F/FF375F',
    description: 'Реролл игры из стима - используется после ролла игры, но до ее запуска.',
  },
  'skip-prison-day': {
    name: 'Хорошее поведение',
    picture: 'https://placehold.co/744x1039/BF5AF2/BF5AF2',
    description:
      "Минус день тюрьмы - можно использовать на клетке 'тюрьма' и 'посещение тюрьмы', как до, так и после ролла игры для того, чтобы покинуть тюрьму.",
  },
  'evade-street-tax': {
    name: 'Сквотируемся',
    picture: 'https://placehold.co/744x1039/30D158/30D158',
    description:
      "Нет 'арендной платы' на улице - Перед попаданием на клетку с чужими постройками, можно активировать карточку и не платить арендную плату.",
  },
  'evade-map-tax': {
    name: 'Без налога',
    picture: 'https://placehold.co/744x1039/FFD60A/FFD60A',
    description:
      "Нет 'налога' за круг - при использовании освобождает от арендной платы после прохождения круга.",
  },
  'game-help-allowed': {
    name: 'Помощь зала',
    picture: 'https://placehold.co/744x1039/FF9F0A/FF9F0A',
    description:
      'Можно попросить помощи у друзей - позволяет в любой момент игры попросить помощи у других игроков, которые могут помочь с деньгами или бонусами.',
  },
};

export const cardTypes = Object.keys(frontendCardsData) as BonusCardType[];

export const mockReviews: GameReviewType[] = [
  {
    gameTitle: 'Haste 1',
    description:
      'Очень весело бывает купаться, и очень интересно в воде плескаться. Это круто - плавать в озере. Лучше ничего, практически, не может быть!',
    rating: 8,
    points: 1000,
    poster: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co9gpd.webp',
    status: 'drop',
    date: new Date(),
    duration: 3600,
  },
  {
    gameTitle: 'Haste 2',
    description:
      'Очень весело бывает купаться, и очень интересно в воде плескаться. Это круто - плавать в озере. Лучше ничего, практически, не может быть!',
    rating: 8,
    points: 1000,
    poster: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co9gpd.webp',
    status: 'completed',
    date: new Date(),
    duration: 4800,
  },
  {
    gameTitle: 'Haste 3',
    description:
      'Очень весело бывает купаться, и очень интересно в воде плескаться. Это круто - плавать в озере. Лучше ничего, практически, не может быть!',
    rating: 8,
    points: 1000,
    poster: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co9gpd.webp',
    status: 'reroll',
    date: new Date(),
    duration: 1800,
  },
];

export const playersFrontendData: Record<string, PlayerFrontendData> = {
  Praden: {
    color: playerColors.red,
  },
  'Player-2': {
    color: playerColors.orange,
  },
  'Player-3': {
    color: playerColors.yellow,
  },
  'Player-4': {
    color: playerColors.green,
  },
  'Player-5': {
    color: playerColors.lightBlue,
  },
  'Player-6': {
    color: playerColors.blue,
  },
  'Player-7': {
    color: playerColors.darkBlue,
  },
  'Player-8': {
    color: playerColors.purple,
  },
};
