import { colors, GameReviewType, PlayerData, SectorData } from "@/types";

export const sectorsData: SectorData[] = [
  {
    id: 1,
    name: "GO",
    position: { x: 0, y: 0 },
    type: "corner",
    color: colors.pastelgreen,
    rollType: "voting",
  },
  {
    id: 2,
    name: "Mediterranean Avenue",
    position: { x: 1, y: 0 },
    type: "property",
    color: colors.brown,
    rollType: "auc",
  },
  {
    id: 3,
    name: "Community Chest 1",
    position: { x: 2, y: 0 },
    type: "community_chest",
    color: colors.pastelgreen,
    rollType: "steam",
  },
  {
    id: 4,
    name: "Baltic Avenue",
    position: { x: 3, y: 0 },
    type: "property",
    color: colors.brown,
    rollType: "auc",
  },
  {
    id: 5,
    name: "Income Tax",
    position: { x: 4, y: 0 },
    type: "property",
    color: colors.brown,
    rollType: "auc",
  },
  {
    id: 6,
    name: "Reading Railroad",
    position: { x: 5, y: 0 },
    type: "railroad",
    color: colors.pastelgreen,
    rollType: "steam",
  },
  {
    id: 7,
    name: "Oriental Avenue",
    position: { x: 6, y: 0 },
    type: "property",
    color: colors.lightblue,
    rollType: "auc",
  },
  {
    id: 8,
    name: "Chance 1",
    position: { x: 7, y: 0 },
    type: "chance",
    color: colors.pastelgreen,
    rollType: "steam",
  },
  {
    id: 9,
    name: "Vermont Avenue",
    position: { x: 8, y: 0 },
    type: "property",
    color: colors.lightblue,
    rollType: "auc",
  },
  {
    id: 10,
    name: "Connecticut Avenue",
    position: { x: 9, y: 0 },
    type: "property",
    color: colors.lightblue,
    rollType: "auc",
  },
  {
    id: 11,
    name: "Jail / Just Visiting",
    position: { x: 10, y: 0 },
    type: "corner",
    color: colors.pastelgreen,
    rollType: "steam",
  },
  {
    id: 12,
    name: "St. Charles Place",
    position: { x: 10, y: 1 },
    type: "property",
    color: colors.pink,
    rollType: "auc",
  },
  {
    id: 13,
    name: "Electric Company",
    position: { x: 10, y: 2 },
    type: "utility",
    color: colors.pastelgreen,
    rollType: "steam",
  },
  {
    id: 14,
    name: "States Avenue",
    position: { x: 10, y: 3 },
    type: "property",
    color: colors.pink,
    rollType: "auc",
  },
  {
    id: 15,
    name: "Virginia Avenue",
    position: { x: 10, y: 4 },
    type: "property",
    color: colors.pink,
    rollType: "auc",
  },
  {
    id: 16,
    name: "Pennsylvania Railroad",
    position: { x: 10, y: 5 },
    type: "railroad",
    color: colors.pastelgreen,
    rollType: "steam",
  },
  {
    id: 17,
    name: "St. James Place",
    position: { x: 10, y: 6 },
    type: "property",
    color: colors.orange,
    rollType: "auc",
  },
  {
    id: 18,
    name: "Community Chest 2",
    position: { x: 10, y: 7 },
    type: "community_chest",
    color: colors.pastelgreen,
    rollType: "steam",
  },
  {
    id: 19,
    name: "Tennessee Avenue",
    position: { x: 10, y: 8 },
    type: "property",
    color: colors.orange,
    rollType: "auc",
  },
  {
    id: 20,
    name: "New York Avenue",
    position: { x: 10, y: 9 },
    type: "property",
    color: colors.orange,
    rollType: "auc",
  },
  {
    id: 21,
    name: "Free Parking",
    position: { x: 10, y: 10 },
    type: "corner",
    color: colors.pastelgreen,
    rollType: "voting",
  },
  {
    id: 22,
    name: "Kentucky Avenue",
    position: { x: 9, y: 10 },
    type: "property",
    color: colors.red,
    rollType: "auc",
  },
  {
    id: 23,
    name: "Chance 2",
    position: { x: 8, y: 10 },
    type: "chance",
    color: colors.pastelgreen,
    rollType: "steam",
  },
  {
    id: 24,
    name: "Indiana Avenue",
    position: { x: 7, y: 10 },
    type: "property",
    color: colors.red,
    rollType: "auc",
  },
  {
    id: 25,
    name: "Illinois Avenue",
    position: { x: 6, y: 10 },
    type: "property",
    color: colors.red,
    rollType: "auc",
  },
  {
    id: 26,
    name: "B. & O. Railroad",
    position: { x: 5, y: 10 },
    type: "railroad",
    color: colors.pastelgreen,
    rollType: "steam",
  },
  {
    id: 27,
    name: "Atlantic Avenue",
    position: { x: 4, y: 10 },
    type: "property",
    color: colors.yellow,
    rollType: "auc",
  },
  {
    id: 28,
    name: "Ventnor Avenue",
    position: { x: 3, y: 10 },
    type: "property",
    color: colors.yellow,
    rollType: "auc",
  },
  {
    id: 29,
    name: "Water Works",
    position: { x: 2, y: 10 },
    type: "utility",
    color: colors.pastelgreen,
    rollType: "steam",
  },
  {
    id: 30,
    name: "Marvin Gardens",
    position: { x: 1, y: 10 },
    type: "property",
    color: colors.yellow,
    rollType: "auc",
  },
  {
    id: 31,
    name: "Go To Jail",
    position: { x: 0, y: 10 },
    type: "corner",
    color: colors.pastelgreen,
    rollType: "steam",
  },
  {
    id: 32,
    name: "Pacific Avenue",
    position: { x: 0, y: 9 },
    type: "property",
    color: colors.green,
    rollType: "auc",
  },
  {
    id: 33,
    name: "North Carolina Avenue",
    position: { x: 0, y: 8 },
    type: "property",
    color: colors.green,
    rollType: "auc",
  },
  {
    id: 34,
    name: "Community Chest 3",
    position: { x: 0, y: 7 },
    type: "community_chest",
    color: colors.pastelgreen,
    rollType: "steam",
  },
  {
    id: 35,
    name: "Pennsylvania Avenue",
    position: { x: 0, y: 6 },
    type: "property",
    color: colors.green,
    rollType: "auc",
  },
  {
    id: 36,
    name: "Short Line",
    position: { x: 0, y: 5 },
    type: "railroad",
    color: colors.pastelgreen,
    rollType: "steam",
  },
  {
    id: 37,
    name: "Chance 3",
    position: { x: 0, y: 4 },
    type: "chance",
    color: colors.pastelgreen,
    rollType: "steam",
  },
  {
    id: 38,
    name: "Park Place",
    position: { x: 0, y: 3 },
    type: "property",
    color: colors.blue,
    rollType: "auc",
  },
  {
    id: 39,
    name: "Luxury Tax",
    position: { x: 0, y: 2 },
    type: "tax",
    color: colors.pastelgreen,
    rollType: "steam",
  },
  {
    id: 40,
    name: "Boardwalk",
    position: { x: 0, y: 1 },
    type: "property",
    color: colors.blue,
    rollType: "auc",
  },
];

export const playersData: PlayerData[] = [
  {
    id: "1",
    current_position: 39,
    name: "Player 1",
    avatar: "https://github.com/shadcn.png",
    color: colors.green,
    sector_ownership: [
      {
        sector_id: 38,
        created_at: Math.ceil(Date.now() / 1000),
        game_length: "2-5",
        game_title: "Haste",
      },
      {
        sector_id: 5,
        created_at: Math.ceil(Date.now() / 1000),
        game_length: "25+",
        game_title: "Haste",
      },
      {
        sector_id: 5,
        created_at: Math.ceil(Date.now() / 1000),
        game_length: "20-25",
        game_title: "Haste",
      },
      {
        sector_id: 5,
        created_at: Math.ceil(Date.now() / 1000),
        game_length: "15-20",
        game_title: "Haste",
      },
      {
        sector_id: 5,
        created_at: Math.ceil(Date.now() / 1000),
        game_length: "10-15",
        game_title: "Haste",
      },
      {
        sector_id: 5,
        created_at: Math.ceil(Date.now() / 1000),
        game_length: "5-10",
        game_title: "Haste",
      },
      {
        sector_id: 5,
        created_at: Math.ceil(Date.now() / 1000),
        game_length: "2-5",
        game_title: "Haste",
      },
      {
        sector_id: 5,
        created_at: Math.ceil(Date.now() / 1000),
        game_length: "drop",
        game_title: "Haste",
      },
    ],
  },
  {
    id: "2",
    current_position: 25,
    name: "Player 2",
    avatar: "https://github.com/shadcn.png",
    color: colors.pink,
    sector_ownership: [
      {
        sector_id: 24,
        created_at: Math.ceil(Date.now() / 1000),
        game_length: "25+",
        game_title: "Haste",
      },
      {
        sector_id: 2,
        created_at: Math.ceil(Date.now() / 1000),
        game_length: "15-20",
        game_title: "Haste",
      },
    ],
  },
  {
    id: "3",
    current_position: 6,
    name: "Player 3",
    avatar: "https://github.com/shadcn.png",
    color: colors.orange,
    sector_ownership: [
      {
        sector_id: 2,
        created_at: Math.ceil(Date.now() / 1000),
        game_length: "5-10",
        game_title: "Haste",
      },
    ],
  },
  {
    id: "4",
    current_position: 40,
    name: "Player 4",
    avatar: "https://github.com/shadcn.png",
    color: colors.yellow,
    sector_ownership: [
      {
        sector_id: 2,
        created_at: Math.ceil(Date.now() / 1000),
        game_length: "drop",
        game_title: "Haste",
      },
    ],
  },
  {
    id: "5",
    current_position: 1,
    name: "Player 5",
    avatar: "https://github.com/shadcn.png",
    color: colors.brown,
    sector_ownership: [
      {
        sector_id: 2,
        created_at: Math.ceil(Date.now() / 1000),
        game_length: "2-5",
        game_title: "Haste",
      },
    ],
  },
  {
    id: "6",
    current_position: 12,
    name: "Player 6",
    avatar: "https://github.com/shadcn.png",
    color: colors.red,
    sector_ownership: [
      {
        sector_id: 10,
        created_at: Math.ceil(Date.now() / 1000),
        game_length: "15-20",
        game_title: "Haste",
      },
    ],
  },
  {
    id: "7",
    current_position: 31,
    name: "Player 7",
    avatar: "https://github.com/shadcn.png",
    color: colors.blue,
    sector_ownership: [
      {
        sector_id: 10,
        created_at: Math.ceil(Date.now() / 1000),
        game_length: "15-20",
        game_title: "Haste",
      },
    ],
  },
  {
    id: "8",
    current_position: 17,
    name: "Player 8",
    avatar: "https://github.com/shadcn.png",
    color: colors.lightblue,
    sector_ownership: [
      {
        sector_id: 10,
        created_at: Math.ceil(Date.now() / 1000),
        game_length: "5-10",
        game_title: "Haste",
      },
    ],
  },
];

export const myPlayerData: PlayerData = playersData[0];

export const mockReviews: GameReviewType[] = [
  {
    gameTitle: "Haste 1",
    description:
      "Очень весело бывает купаться, и очень интересно в воде плескаться. Это круто - плавать в озере. Лучше ничего, практически, не может быть!",
    rating: 8,
    points: 1000,
    poster: "https://images.igdb.com/igdb/image/upload/t_cover_big/co9gpd.webp",
    status: "drop",
    date: new Date(),
  },
  {
    gameTitle: "Haste 2",
    description:
      "Очень весело бывает купаться, и очень интересно в воде плескаться. Это круто - плавать в озере. Лучше ничего, практически, не может быть!",
    rating: 8,
    points: 1000,
    poster: "https://images.igdb.com/igdb/image/upload/t_cover_big/co9gpd.webp",
    status: "completed",
    date: new Date(),
  },
  {
    gameTitle: "Haste 3",
    description:
      "Очень весело бывает купаться, и очень интересно в воде плескаться. Это круто - плавать в озере. Лучше ничего, практически, не может быть!",
    rating: 8,
    points: 1000,
    poster: "https://images.igdb.com/igdb/image/upload/t_cover_big/co9gpd.webp",
    status: "reroll",
    date: new Date(),
  },
];
